// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int repetition=Integer.parseInt(args[0]);
	   int greaterThen=0;
	   int lessThen=0;
	   int i=0;
	   double ratio;
	   while (i<repetition){
		double randomNum=Math.random();
		if (randomNum>0.5){
			greaterThen++;
		}else{
			lessThen++;
		}
		System.out.println(randomNum);
		i++;
	   }
	   System.out.println(">0.5 : "+greaterThen+" times");
	   System.out.println("<=0.5 : "+lessThen+" times");
	   if (greaterThen>lessThen&&lessThen!=0){
          ratio= (lessThen/(double)greaterThen);
		  System.out.println(ratio);

	   }else if(lessThen>=greaterThen&&greaterThen!=0){
		ratio= greaterThen/(double)lessThen;
		System.out.println(ratio);
	   }else if (lessThen==0||greaterThen==0){
		System.out.println("Odd results");
	   }

	   
	}
}
